### ISSUE TITLE
Production Ready?

### ISSUE THREAD

**Issue by mindware** [Fubelly/rubyflake#2] opened 2014-08-25 20:18 UTC
Anyone using this in production? Is it production ready? 
It says it is a simplified version of snowflake. Are you using the exact snowflake algorithm or is this a watered-down version?

**Comment by joallard** [comment] 2015-02-14 21:03
I put a test in #3, that should be a beginning. If you want some kind of "production ready" assurance, maybe some other tests would be good.

**Comment by mindware** [comment] 2015-03-24 05:28
Thanks for the submissions. Let's see if @mtthgn comes back to merge it, since this is under @fubelly it's not getting much attention it seems.

**Comment by joallard** [comment] 2015-03-24 15:13
I appreciate the spirit, but I think this thread is a kind of non-issue. Seeing my PR has been merged, I think this is a good time to close it, and maybe add some tests if you see things that could break. The issue is kind-of not actionable. Staple #4 and we'll be good to go.

**Closed** 2015-03-24 15:48 UTC
